homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

weather:
   - platform: buienradar
     name: 'arnhem'
     latitude: 52.07
     longitude: 5.88

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/ 

# Set lovelace to yaml mode instead of UI
lovelace:
  mode: yaml
  resources:
    - url: /local/custom-lovelace/weather-card/weather-card.js
      type: module
    - url: /local/custom-lovelace/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.9.3
      type: module
    - url: /local/custom-lovelace/mini-media-player-bundle.js?v=1.5.2
      type: module
    - url: /local/custom-lovelace/compact-custom-header/custom-header.js?v=1.3.8
      type: module

# Enables configuration section in UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

recorder:
  purge_keep_days: 2
  purge_interval: 1
  db_url: sqlite:///home/homeassistant/.homeassistant/home-assistant_v2.db

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Person integration
person:

# IOS app integration
mobile_app:

# Hue bridge config
hue:
  bridges:
    - host: 192.168.178.20

# Add to Homekit
homekit:
  auto_start: False
  filter:
    include_entities:
       - alarm_control_panel.home_alarm
       - switch.aeon_labs_zw080_siren_gen5_switch
       - switch.aeon_labs_zw080_siren_gen5_switch_3
       - sensor.br_temperature_2
       - media_player.xbox_one
       - media_player.mybraviatv
       - cover.rolluiken_kamer_rens
       - cover.rolluiken_kamer_maxime
       - cover.rolgordijn_voorraam
       - cover.lamellendak
  entity_config:
    media_player.xbox_one:
      feature_list:
         - feature: on_off
    alarm_control_panel.home_alarm:
      code: !secret alarm_code

# DuckDNS for remote access to HASS
duckdns:
  domain: hass-vansteen
  access_token: !secret duck_access_token

#SSL (LE) settings
http:
  ssl_certificate: /etc/letsencrypt/live/hass-vansteen.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hass-vansteen.duckdns.org/privkey.pem
  base_url: !secret hass_url
  #  api_password: !secret http_api_password

# Cloud
cloud:

# Alarm panel config
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 5
    delay_time: 5
    trigger_time: 5
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 20
      delay_time: 10
    armed_away:
      pending_time: 20
      delay_time: 10

# Text to speech
tts:
  - platform: google_translate
    language: 'nl'

# Media Player component
media_player:
  - platform: braviatv_psk
    host: 192.168.178.24
    psk: !secret braviatv_psk
    mac: 90:48:9a:4c:7e:4e
    amp: True
    android: False
    sourcefilter:
      - ' HD'
      - HDMI
    name: MyBraviaTV
  - platform: xboxone
    device: !secret xbox_live_id
    ip_address: 192.168.178.38
    name: Xbox One

stream:

camera:
  - platform: buienradar

# Tado thermostats
tado:
  username: !secret tado_user
  password: !secret tado_pass

# Roomba stofzuiger
#vacuum:
#  - platform: roomba
#    host: 192.168.178.46
#    username: !secret roomba_user
#    password: !secret roomba_pass

cover:
  - platform: rfxtrx
    automatic_add: false
    signal_repetitions: 1 # signal_repetitions: 1 for the Somfy covers (avoid to stop the motion after start)
    devices:
      071a000000000101: # RFY
        name: Rolgordijn voorraam
      071a000000000202: # RFY
        name: Lamellendak
  - platform: group
    name: Rolluiken kamer Rens
    entities:
      - cover.aeon_labs_zw141_nano_shutter_level # Kantelkiepraam
      - cover.aeon_labs_zw141_nano_shutter_level_2 # Zijraam rechts
      - cover.aeon_labs_zw141_nano_shutter_level_3 # Raam Links 
  - platform: group
    name: Rolluiken kamer Maxime
    entities:
      - cover.aeon_labs_zw141_nano_shutter_level_4 #Kantelkiepraam
      - cover.aeon_labs_zw141_nano_shutter_level_5 # Raam links
  - platform: group
    name: Alle rolluiken
    entities:
      - cover.aeon_labs_zw141_nano_shutter_level # Kantelkiepraam Rens
      - cover.aeon_labs_zw141_nano_shutter_level_2 # Zijraam rechts Rens
      - cover.aeon_labs_zw141_nano_shutter_level_3 # Raam Links Rens
      - cover.aeon_labs_zw141_nano_shutter_level_4 #Kantelkiepraam Maxime
      - cover.aeon_labs_zw141_nano_shutter_level_5 # Raam links Maxime

# Sensors
sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure

binary_sensor:
  - platform: huesensor
  - platform: template
    sensors:
      fuse_box_door:
        friendly_name: "Meterkast deur"
        device_class: door
        value_template: >-
          {% if is_state('sensor.aeotec_limited_zwa008_door_window_sensor_7_access_control', '22') %}
            open
          {% elif is_state('sensor.aeotec_limited_zwa008_door_window_sensor_7_access_control', '23') %}
            closed
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.aeotec_limited_zwa008_door_window_sensor_7_access_control', '22') %}
            mdi:door-open
          {% elif is_state('sensor.aeotec_limited_zwa008_door_window_sensor_7_access_control', '23') %}
            mdi:door-closed-lock
          {% else %}
            mdi:alert
          {% endif %}
      sliding_door:
        friendly_name: "Schuifpui"
        device_class: door
        value_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '22') %}
            open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '23') %}
            closed
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '22') %}
            mdi:door-open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '23') %}
            mdi:door-closed-lock
          {% else %}
            mdi:alert
          {% endif %}
      front_door:
        friendly_name: "Voordeur"
        device_class: door
        value_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_2', '22') %}
            open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_2', '23') %}
            closed
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_2', '22') %}
            mdi:door-open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_2', '23') %}
            mdi:door-closed-lock
          {% else %}
            mdi:alert
          {% endif %}
      scullery_door:
        friendly_name: "Bijkeukendeur"
        device_class: door
        value_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_3', '22') %}
            open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_3', '23') %}
            closed
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_3', '22') %}
            mdi:door-open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_3', '23') %}
            mdi:door-closed-lock
          {% else %}
            mdi:alert
          {% endif %}
      storage_door:
        friendly_name: "Bergingdeur"
        device_class: door
        value_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_4', '22') %}
            open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_4', '23') %}
            closed
          {% else %}
            unknown
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_4', '22') %}
            mdi:door-open
          {% elif is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control_4', '23') %}
            mdi:door-closed-lock
          {% else %}
            mdi:alert
          {% endif %}

# Input_boolean used for Doorbird conditional card in frontend
input_boolean:
  visitor_ring:
    name: 'De voordeur bel gaat!'
    initial: off

# Light steps for dimming feature Wallmote
input_number:
  light_step:
    name: 'Step the lights this much'
    initial: 64
    min: 1
    max: 128
    step: 6

  light_minimum:
    name: 'No dimmer than this'
    initial: 5
    min: 1
    max: 255
    step: 1

  light_maximum:
    name: 'No brighter than this'
    initial: 255
    min: 50
    max: 255
    step: 1

# RFXtrx config for sompfy remotes
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433XL_DO4GUAEL-if00-port0

# Z-Wave configuration
zwave:

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
