title: Home

views:
  - badges:
      - device_tracker.iphone_x_alexander_2
      - device_tracker.iphone
      - sensor.battery_level
      - alarm_control_panel.home_alarm
      - sun.sun
    cards:
      - card:
          cards:
            - cards:
                - entity: lock.poly_control_danalock_v3_btze_locked
                  hold_action:
                    action: none
                  icon: 'mdi:lock-open'
                  name: Open Door
                  tap_action:
                    action: call-service
                    service: lock.unlock
                    service_data:
                      entity_id: lock.poly_control_danalock_v3_btze_locked
                  theme: Backend-selected
                  type: entity-button
                - entity: input_boolean.visitor_ring
                  hold_action:
                    action: none
                  icon: 'mdi:cancel'
                  name: Ignore
                  tap_action:
                    action: toggle
                  theme: Backend-selected
                  type: entity-button
              type: horizontal-stack
            - entity: camera.front_door_live
              type: picture-entity
          type: vertical-stack
        conditions:
          - entity: input_boolean.visitor_ring
            state: 'on'
        type: conditional
      - entity: media_player.speakers
        type: custom:mini-media-player
        icon: "mdi:speaker"
        hide:
          power: true
        artwork: cover
      - entity: weather.arnhem
        current: true
        details: false
        forecast: true
        type: custom:weather-card
      - cards:
          - entity: sensor.woonkamer_temperature
            graph: line
            icon: 'mdi:sofa'
            name: Tado Woonkamer
            type: sensor
          - entity: sensor.woonkamer_humidity
            graph: line
            icon: 'mdi:sofa'
            name: Humidity woonkamer
            type: sensor
        type: horizontal-stack
      - cards:
          - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_2
            graph: line
            icon: 'mdi:door'
            name: Sensor voordeur
            type: sensor
          - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
            graph: line
            icon: 'mdi:door'
            name: Sensor schuifpui
            type: sensor
        type: horizontal-stack
      - entities: []
        entity: lock.poly_control_danalock_v3_btze_locked
        state_image:
          locked: /local/danalock_closed.png
          unlocked: /local/danalock_open.png
        tap_action:
          action: more-info
        title: Voordeur
        type: picture-glance
      - cards:
          - entities: []
            entity: media_player.mybraviatv
            hold_action:
              action: more-info
            state_image:
              'off': /local/tv_off-800.png
              'on': /local/tv_on-800.png
            tap_action:
              action: toggle
            title: Sony Bravia
            type: picture-glance
          - entities: []
            entity: media_player.xbox_one
            hold_action:
              action: more-info
            state_image:
              'off': /local/xbox_off-800.png
              'on': /local/xbox_on-800.png
              'unknown': /local/xbox_on-800.png
            tap_action:
              action: toggle
            title: Xbox One X
            type: picture-glance
        type: horizontal-stack
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_away
          - arm_night
        type: alarm-panel
    icon: 'mdi:shield-home'
    panel: false
    title: Security
  - badges:
      - binary_sensor.front_door
      - binary_sensor.fuse_box_door
      - binary_sensor.sliding_door
      - binary_sensor.scullery_door
      - binary_sensor.storage_door
    cards:
      - cards:
          - entity: camera.front_door_last_motion
            type: picture-entity
          - entity: camera.front_door_last_ring
            type: picture-entity
        type: horizontal-stack
      - columns: 2
        entities:
          - entity: camera.front_door_live
          - entity: lock.poly_control_danalock_v3_btze_locked
        show_icon: true
        show_state: true
        title: Status voordeur
        type: glance
      - columns: 2
        entities:
          - entity: cover.lamellendak
          - entity: cover.rolgordijn_voorraam
          - entity: cover.rolluiken_kamer_rens
          - entity: cover.rolluiken_kamer_maxime
        show_icon: true
        show_state: true
        title: Status ramen & lamellendak
        type: glance
    icon: 'mdi:cctv'
    path: cameras
    title: Camera's
  - badges: []
    cards:
      - cards:
          - entity: script.turn_off_indoor_lights
            icon: 'mdi:lightbulb-group-off-outline'
            name: Alle lampen uit
            tap_action:
              action: call-service
              service: script.turn_off_downstair_lights
            type: entity-button
          - entity: light.woonkamer
            name: Dimmer
            type: light
        type: horizontal-stack
      - entities:
          - entity: script.1549758951085
            icon: 'mdi:lightbulb-on-outline'
            name: Helder
            tap_action:
              action: toggle
          - entity: script.1549758920504
            icon: 'mdi:television'
            name: TV kijken
            tap_action:
              action: toggle
          - entity: script.1549758477586
            icon: 'mdi:xbox'
            name: Gamen
            tap_action:
              action: toggle
        show_state: false
        title: Hue Scenes
        type: glance
      - columns: 5
        entities:
          - entity: light.woonkamer
            hold_action:
              action: more-info
            icon: 'mdi:sofa'
            name: Woonkamer
            tap_action:
              action: toggle
          - entity: light.eetkamer
            hold_action:
              action: more-info
            icon: 'mdi:silverware-fork-knife'
            name: Eetkamer
            tap_action:
              action: toggle
          - entity: light.keuken
            hold_action:
              action: more-info
            icon: 'mdi:stove'
            tap_action:
              action: toggle
          - entity: light.hal
            hold_action:
              action: more-info
            icon: 'mdi:stairs'
            name: Hal
            tap_action:
              action: toggle
          - entity: light.overloop
            hold_action:
              action: more-info
            icon: 'mdi:wall-sconce-flat'
            name: Overloop
            tap_action:
              action: toggle
          - entity: light.kamer_rens
            hold_action:
              action: more-info
            icon: 'mdi:human-male-boy'
            name: Kamer Rens
            tap_action:
              action: toggle
          - entity: light.kamer_maxime
            hold_action:
              action: more-info
            icon: 'mdi:human-female-girl'
            name: Kamer Maxime
            tap_action:
              action: toggle
          - entity: light.buiten
            hold_action:
              action: more-info
            icon: 'mdi:tree'
            name: Buiten
            tap_action:
              action: toggle
          - entity: light.carport
            hold_action:
              action: more-info
            icon: 'mdi:car'
            name: Carport
            tap_action:
              action: toggle
          - entity: light.terras
            hold_action:
              action: more-info
            icon: 'mdi:home-roof'
            name: Terras
            tap_action:
              action: toggle
        show_icon: true
        show_name: true
        show_state: false 
        title: Hue verlichting
        type: glance
    icon: 'mdi:lightbulb'
    title: Lights
  - badges: []
    cards:
      - cards:
          - entity: media_player.mybraviatv
            type: custom:mini-media-player
            hide:
              volume: true
          - entity: media_player.speakers
            type: custom:mini-media-player 
            icon: 'mdi:speaker'
          - entity: media_player.xbox_one
            type: custom:mini-media-player
            icon: 'mdi:xbox'
          - entity: media_player.woonkamer
            type: custom:mini-media-player
            icon: 'mdi:airplay'
            artwork: full-cover
            hide:
              volume: true
        type: vertical-stack
    icon: 'mdi:airplay'
    panel: false
    title: Mediaplayers
  - badges: []
    cards:
      - type: vertical-stack      
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.woonkamer
            step_size: 1
            icon: 'mdi:sofa'
            sensors:
              - entity: sensor.hue_motion_sensor_1_temperature_2
                name: Keuken
              - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
                name: Schuifpui
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - entities: 
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_2
                type: custom:mini-graph-card
                name: Sensor Voordeur
                hours_to_show: 48
              - entities:
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
                type: custom:mini-graph-card
                name: Sensor schuifpui
                hours_to_show: 48
            type: horizontal-stack
          - cards:
              - entities:
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_3
                type: custom:mini-graph-card
                name: Sensor Bijkeuken
                hours_to_show: 48
              - entities: 
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_4
                type: custom:mini-graph-card
                name: Sensor Berging
                hours_to_show: 48
            type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.1e_verdieping
            step_size: 1
            icon: 'mdi:home-roof'
            sensors:
              - entity: sensor.1e_verdieping_temperature
                name: 1e Verdieping
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.1e_verdieping_temperature
                    name: Temperature
                    color: #e74c3c
                  - entity: sensor.1e_verdieping_humidity
                    name: Humidity
                    color: #1e90ff
                    y_axis: secondary
                name: 1e Verdieping (last 72 hours)
                hours_to_show: 72
                line_width: 3
            title: 1e Verdieping
            type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.voorzolder
            step_size: 1
            icon: 'mdi:home-roof'
            sensors:
              - entity: sensor.voorzolder_temperature
                name: Voorzolder
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.voorzolder_temperature
                    name: Temperature
                    color: #e74c3c
                  - entity: sensor.voorzolder_humidity
                    name: Humidity
                    color: #1e90ff
                    y_axis: secondary
                name: Voorzijde zolder (last 72 hours)
                hours_to_show: 72
                line_width: 3
            title: Zolder
            type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.achterzolder
            step_size: 1
            icon: 'mdi:home-roof'
            sensors:
              - entity: sensor.achterzolder_temperature
                name: Achterzolder
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.achterzolder_temperature
                    name: Temperature
                    color: #e74c3c
                  - entity: sensor.achterzolder_humidity
                    name: Humidity
                    color: #1e90ff
                    y_axis: secondary
                name: Achterzijde zolder (last 72 hours)
                hours_to_show: 72
                line_width: 3
            title: Zolder
            type: horizontal-stack
    icon: "mdi:fire"
    title: Heating
  - badges: []
    cards:
      - type: glance
        entities:
          - entity: switch.qubino_goap_zmnhbdx_flush_2_relays_switch
            name: Verlichting
            icon: "mdi:led-strip"
            tap_action:
              action: toggle
          - entity: switch.qubino_goap_zmnhbdx_flush_2_relays_switch_2
            name: Verwarming
            icon: "mdi:fire"
            tap_action:
              action: toggle
        title: Spiegel
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.qubino_goap_zmnhbdx_flush_2_relays_power
            name: Mirror Ledstrip (W)
            color: "#1e90ff"
          - entity: sensor.qubino_goap_zmnhbdx_flush_2_relays_power_2
            name: Mirror Heating (W)
            color: "#ff0000"
        name: Power consumption (last 12 hours)
        hours_to_show: 12
        line_width: 3
    icon: "mdi:shower"
    title: Bathroom
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.hue_motion_motion_keuken
          - entity: binary_sensor.hue_motion_sensor_motion_overloop
        title: Hue motion sensors
        type: entities
      - entities:
          - entity: light.hal
          - entity: light.woonkamer
          - entity: light.eetkamer
          - entity: light.keuken
          - entity: light.overloop
          - entity: light.kamer_rens
          - entity: light.kamer_maxime
          - entity: light.terras
          - entity: light.buiten
          - entity: light.carport
        title: Light
        type: entities
      - entities:
          - entity: zwave.aeon_labs_zw090_z_stick_gen5_eu
          - entity: zwave.aeon_labs_zw117_range_extender_6
          - entity: zwave.aeon_labs_zw129_wallmote_duo
          - entity: zwave.aeon_labs_zw130_wallmote_quad
          - entity: zwave.aeon_labs_zw130_wallmote_quad_2
          - entity: zwave.aeon_labs_zw130_wallmote_quad_3
          - entity: zwave.aeon_labs_zw080_siren_gen5
          - entity: zwave.aeon_labs_zw080_siren_gen5_2
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2_2
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2_3
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2_4
          - entity: zwave.aeotec_limited_zwa008_door_window_sensor_7
          - entity: zwave.poly_control_danalock_v3_btze
          - entity: zwave.qubino_goap_zmnhbdx_flush_2_relays
          - entity: zwave.aeon_labs_zw141_nano_shutter
          - entity: zwave.aeon_labs_zw141_nano_shutter_2
          - entity: zwave.aeon_labs_zw141_nano_shutter_3
          - entity: zwave.aeon_labs_zw141_nano_shutter_4
          - entity: zwave.aeon_labs_zw141_nano_shutter_5
        title: Z-Wave
        type: entities
    icon: 'mdi:settings'
    title: Settings

custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  swipe_animate: fade
  #  swipe_prevent_default: true
  swipe_prevent_default: false
  compact_mode: true
  voice_hide: true
  #  button_text:
  #    options: '{{ hours24 }}:{{ minutesLZ }}'

background: var(--background-image)

