title: Home
views:
  - badges:
      - device_tracker.iphone_x_alexander_2
      - device_tracker.iphone
      - sensor.battery_level
      - alarm_control_panel.home_alarm
      - sun.sun
    cards:
      - cards:
          - entity: group.all_lights
            icon: 'mdi:lightbulb-outline'
            icon_height: 157px
            name: Alle lampen uit
            tap_action:
              action: call-service
              service: light.turn_off
            type: entity-button
          - entity: light.woonkamer
            name: Woonkamer
            type: light
        type: horizontal-stack
        entity: weather.br_unknown_station
        current: true
        details: false
        forecast: true
        type: custom:weather-card
      - cards:
          - entity: sensor.woonkamer_temperature
            graph: line
            icon: 'mdi:sofa'
            name: Tado Woonkamer
            type: sensor
          - entity: sensor.woonkamer_humidity
            graph: line
            icon: 'mdi:sofa'
            name: Humidity woonkamer
            type: sensor
        type: horizontal-stack
      - cards:
          - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_2
            graph: line
            icon: 'mdi:door'
            name: Sensor voordeur
            type: sensor
          - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
            graph: line
            icon: 'mdi:door'
            name: Sensor schuifpui
            type: sensor
        type: horizontal-stack
      - cards:
          - entities: []
            entity: media_player.mybraviatv
            hold_action:
              action: more-info
            state_image:
              'off': /local/tv_off-800.png
              'on': /local/tv_on-800.png
            tap_action:
              action: toggle
            title: Sony Bravia
            type: picture-glance
          - entities: []
            entity: media_player.xbox_one
            hold_action:
              action: more-info
            state_image:
              'off': /local/xbox_off-800.png
              'on': /local/xbox_on-800.png
              'unknown': /local/xbox_on-800.png
            tap_action:
              action: toggle
            title: Xbox One X
            type: picture-glance
        type: horizontal-stack
      - entities: []
        entity: lock.poly_control_danalock_v3_btze_locked
        state_image:
          locked: /local/danalock_closed.jpg
          unlocked: /local/danalock_open.jpg
        tap_action:
          action: more-info
        title: Voordeur
        type: picture-glance
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: alarm_control_panel.home_alarm
        states:
          - arm_away
          - arm_night
        type: alarm-panel
    icon: 'mdi:shield-home'
    panel: false
    title: Security
  - badges:
      - camera.front_door_last_motion
      - camera.front_door_last_ring
      - binary_sensor.front_door
      - binary_sensor.fuse_box_door
      - binary_sensor.sliding_door
      - binary_sensor.scullery_door
    cards:
      - columns: 2
        entities:
          - entity: cover.rolluiken_kamer_rens
          - entity: cover.rolluiken_kamer_maxime
          - entity: lock.poly_control_danalock_v3_btze_locked
        show_icon: true
        show_state: true
        title: Status van ramen & deuren
        type: glance
      - cards:
          - entity: lock.poly_control_danalock_v3_btze_locked
            icon: 'mdi:door-open'
            name: Open Frontdoor
            tap_action:
              action: call-service
              service: lock.unlock
            type: entity-button
          - entity: lock.poly_control_danalock_v3_btze_locked
            icon: 'mdi:door-closed-lock'
            name: Close Frontdoor
            tap_action:
              action: call-service
              service: lock.lock
            type: entity-button
        type: horizontal-stack
      - card:
          cards:
            - entity: camera.front_door_live
              type: picture-entity
            - cards:
                - entity: lock.poly_control_danalock_v3_btze_locked
                  hold_action:
                    action: none
                  icon: 'mdi:lock-open'
                  name: Open Door
                  tap_action:
                    action: call-service
                    service: lock.unlock
                  theme: Backend-selected
                  type: entity-button
                - entity: input_boolean.visitor_ring
                  hold_action:
                    action: none
                  icon: 'mdi:cancel'
                  name: Ignore
                  tap_action:
                    action: toggle
                  theme: Backend-selected
                  type: entity-button
              type: horizontal-stack
          type: vertical-stack
        conditions:
          - entity: input_boolean.visitor_ring
            state: 'on'
        type: conditional
    icon: 'mdi:cctv'
    path: cameras
    title: Camera's
  - badges: []
    cards:
      - cards:
          - entity: group.all_lights
            icon: 'mdi:lightbulb-outline'
            icon_height: 153px
            name: Alle lampen uit
            tap_action:
              action: call-service
              service: light.turn_off
            type: entity-button
          - entity: light.woonkamer
            name: Dimmer
            type: light
        type: horizontal-stack
      - entities:
          - entity: script.1549758951085
            icon: 'mdi:lightbulb-on-outline'
            name: Alle lampen aan
            tap_action:
              action: toggle
          - entity: script.1549758920504
            icon: 'mdi:television'
            name: TV kijken
            tap_action:
              action: toggle
          - entity: script.1549758477586
            icon: 'mdi:xbox'
            name: Gamen
            tap_action:
              action: toggle
        show_state: false
        title: Hue Scenes
        type: glance
      - columns: 3
        entities:
          - entity: light.hal
            hold_action:
              action: more-info
            icon: 'mdi:stairs'
            name: Hal
            tap_action:
              action: toggle
          - entity: light.woonkamer
            hold_action:
              action: more-info
            icon: 'mdi:sofa'
            name: Woonkamer
            tap_action:
              action: toggle
          - entity: light.eetkamer
            hold_action:
              action: more-info
            icon: 'mdi:silverware-fork-knife'
            name: Eetkamer
            tap_action:
              action: toggle
          - entity: light.keuken
            hold_action:
              action: more-info
            icon: 'mdi:stove'
            tap_action:
              action: toggle
          - entity: light.overloop
            hold_action:
              action: more-info
            icon: 'mdi:wall-sconce-flat'
            name: Overloop
            tap_action:
              action: toggle
          - entity: light.kamer_rens
            hold_action:
              action: more-info
            icon: 'mdi:human-male-boy'
            name: Kamer Rens
            tap_action:
              action: toggle
          - entity: light.kamer_maxime
            hold_action:
              action: more-info
            icon: 'mdi:human-female-girl'
            name: Kamer Maxime
            tap_action:
              action: toggle
          - entity: light.buiten
            hold_action:
              action: more-info
            icon: 'mdi:tree'
            name: Buiten
            tap_action:
              action: toggle
          - entity: light.carport
            hold_action:
              action: more-info
            icon: 'mdi:car'
            name: Carport
            tap_action:
              action: toggle
          - entity: light.terras
            hold_action:
              action: more-info
            icon: 'mdi:home-roof'
            name: Terras
            tap_action:
              action: toggle
        show_icon: true
        show_name: true
        show_state: false 
        title: Hue verlichting
        type: glance
    icon: 'mdi:lightbulb'
    title: Lights
  - badges: []
    cards:
      - type: vertical-stack      
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.woonkamer
            step_size: 1
            icon: 'mdi:sofa'
            sensors:
              - entity: sensor.woonkamer_temperature
                name: Tado
              - entity: sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
                name: Schuifpui
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - entities: 
                  - sensor.woonkamer_temperature
                type: custom:mini-graph-card
                name: Tado woonkamer
                hours_to_show: 48
              - entities:
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature
                type: custom:mini-graph-card
                name: Sensor schuifpui
                hours_to_show: 48
            type: horizontal-stack
          - cards:
              - entities: 
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_2
                type: custom:mini-graph-card
                name: Sensor Voordeur
                hours_to_show: 48
              - entities:
                  - sensor.fibaro_system_fgdw002_door_opening_sensor_2_temperature_3
                type: custom:mini-graph-card
                name: Sensor Bijkeuken
                hours_to_show: 48
            type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.voorzolder
            step_size: 1
            icon: 'mdi:home-roof'
            sensors:
              - entity: sensor.voorzolder_temperature
                name: Voorzolder
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.voorzolder_temperature
                    name: Temperature
                    color: #e74c3c
                  - entity: sensor.voorzolder_humidity
                    name: Humidity
                    color: #1e90ff
                    y_axis: secondary
                name: Voorzijde zolder (last 48 hours)
                hours_to_show: 48
                line_width: 3
            title: Zolder
            type: horizontal-stack
      - type: vertical-stack
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.achterzolder
            step_size: 1
            icon: 'mdi:home-roof'
            sensors:
              - entity: sensor.achterzolder_temperature
                name: Achterzolder
              - attribute: current_humidity
                name: Luchtvochtigheid
          - cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.achterzolder_temperature
                    name: Temperature
                    color: #e74c3c
                  - entity: sensor.achterzolder_humidity
                    name: Humidity
                    color: #1e90ff
                    y_axis: secondary
                name: Achterzijde zolder (last 48 hours)
                hours_to_show: 48
                line_width: 3
            title: Zolder
            type: horizontal-stack
    icon: "mdi:radiator"
    title: Heating
  - badges: []
    cards:
      - cards:
          - entity: media_player.mybraviatv
            type: media-control
          - entity: media_player.speakers
            type: media-control
          - entity: media_player.xbox_one
            type: media-control
          - entity: media_player.woonkamer
            type: media-control
        type: vertical-stack
    icon: 'mdi:airplay'
    panel: false
    title: Mediaplayers
  - badges: []
    cards:
      - entities:
          - entity: light.hal
          - entity: light.woonkamer
          - entity: light.eetkamer
          - entity: light.keuken
          - entity: light.overloop
          - entity: light.kamer_rens
          - entity: light.kamer_maxime
          - entity: light.terras
          - entity: light.carport
        title: Light
        type: entities
      - entities:
          - entity: zwave.aeon_labs_zw090_z_stick_gen5_eu
          - entity: zwave.aeon_labs_zw117_range_extender_6
          - entity: zwave.aeon_labs_zw129_wallmote_duo
          - entity: zwave.aeon_labs_zw130_wallmote_quad
          - entity: zwave.aeon_labs_zw130_wallmote_quad_2
          - entity: zwave.aeon_labs_zw130_wallmote_quad_3
          - entity: zwave.aeon_labs_zw080_siren_gen5
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2_2
          - entity: zwave.fibaro_system_fgdw002_door_opening_sensor_2_3
          - entity: zwave.aeotec_limited_zwa008_door_window_sensor_7
          - entity: zwave.poly_control_danalock_v3_btze
          - entity: zwave.aeon_labs_zw141_nano_shutter
          - entity: zwave.aeon_labs_zw141_nano_shutter_2
          - entity: zwave.aeon_labs_zw141_nano_shutter_3
          - entity: zwave.aeon_labs_zw141_nano_shutter_4
          - entity: zwave.aeon_labs_zw141_nano_shutter_5
        title: Z-Wave
        type: entities
    icon: 'mdi:settings'
    title: Settings
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/custom-lovelace/simple-thermostat/simple-thermostat.js
    type: module
  - url: /local/custom-lovelace/mini-graph-card-bundle.js
    type: module
