##### Alarm is TRIGGERED automations ########################
- alias: Actions when alarm is triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    # Give voice warning that alarm is triggered
    - service: script.sonos_say
      data:
        sonos_entity: media_player.speakers
        volume: 0.5
        message: 'ATTENTIE!! Inbraak gedetecteerd, over 5 seconden gaat het alarm af.'
    # Wait for 15 seconds and sound the alarm
    - delay:
        seconds: 10
    # Send notifications to Alexander and Corinne
    - service: notify.mobile_app_iphone_x_alexander
      data:
        title: 'ALARM !!!'
        message: 'The alarm is TRIGGERED at {{now().strftime("%H:%M %d-%m-%Y")}}'
        data:
          subtitle: 'TRIGGERED'
    - service: notify.mobile_app_iphone
      data:
        title: 'ALARM !!!'
        message: 'The alarm is TRIGGERED at {{now().strftime("%H:%M %d-%m-%Y")}}'
        data:
          subtitle: 'TRIGGERED'
    # Flash lights in livingroom and hallway
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        rgb_color: [255,0,0]
        brightness: 255
        flash: long
    - service: light.turn_on
      data:
        entity_id: light.hal
    - service: light.turn_on
      data:
        entity_id: light.hal
        rgb_color: [255,0,0]
        brightness: 255
        flash: long
    - service: switch.turn_on
      data:
        entity_id: switch.aeon_labs_zw080_siren_gen5_switch_3
