############## Doorbird ###################
# Event Catcher Automation to trigger showing Door UI in frontend via conditional card
- alias: Doorbird Ring
  initial_state: true
  trigger:
    - platform: event
      event_type: doorbird_front_door_doorbell
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.visitor_ring
    - service: persistent_notification.create
      data:
        title: 'De deurbel gaat'
        message: 'Er staat iemand voor de voordeur..'

# Cancel Automation to reset input_boolean when no action was taken for 3 minutes
- alias: Cancel Ring after 30 seconds
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.visitor_ring
      from: 'off'
      to: 'on'
      for: '00:03:00'
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: input_boolean.visitor_ring

# Event Catcher automation when motion is detected
- alias: Doorbird motion
  initial_state: true
  trigger:
    - platform: event
      event_type: doorbird_front_door_motion
  condition:
    - condition: state
      entity_id: light.buiten 
      state: 'on'
  action:
          #    - service: light.turn_on
          #      data:
          #        entity_id: light.buiten
          #        transition: 1
          #        brightness: 255
    - service: hue.hue_activate_scene
      data:
        group_name: 'Buiten'
        scene_name: 'Helder'
    - delay: '00:01:00'
    - service: hue.hue_activate_scene
      data:
        group_name: 'Buiten'
        scene_name: 'Huis uitlichten'

# Event Catcher Automation when RFID card is scanned
- alias: Doorbird RFID
  trigger:
    - platform: event
      event_type: doorbird_front_door_rfid_card_scanned
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_code
    - service: script.sonos_say
      data:
        sonos_entity: media_player.speakers
        volume: 0.3
        message: 'RFID tag is geldig.. Welkom thuis'
        delay: '00:00:03'
    - service: notify.mobile_app_iphone_x_alexander
      data:
        title: 'RFID card gescanned'
        subtitle: 'RFID card herkend..'
        message: 'Card gescanned om: {{now().strftime("%H:%M %d-%m-%Y")}}'
