- alias: "Open roof with sunshine"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: +14.0
  condition:
    - condition: template
      value_template: "{{ not is_state('weather.br_unknown_station', 'rainy') }}"
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: numeric_state
      entity_id: sensor.br_temperature_2
      below: 25
    - condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.iphone_x_alexander_2
          state: 'home'
        - condition: state
          entity_id: device_tracker.iphone
          state: 'home'
  action:
      service: script.turn_on
      entity_id: script.open_veraluxe_roof_half

- alias: "Close roof when it turns dark"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: -8.0
  action:
    service: cover.close_cover
    entity_id: cover.lamellendak
