- alias: Button 1 tap
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 1
      scene_data: 0
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.rolluiken_kamer_maxime
- alias: Button 1 hold
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 1
      scene_data: 2
  action:
  - service: cover.stop_cover
    data:
      entity_id: cover.rolluiken_kamer_maxime
- alias: Button 2 tap
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 2
      scene_data: 0
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.rolluiken_kamer_rens
- alias: Button 2 hold
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 2
      scene_data: 2
  action:
  - service: cover.stop_cover
    data:
      entity_id: cover.rolluiken_kamer_rens
- alias: Button 3 tap
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 3
      scene_data: 0
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.rolluiken_kamer_maxime
- alias: Button 3 hold
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 3
      scene_data: 2
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Eetkamer"
      scene_name: "Helder"
- alias: Button 4 tap
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 4
      scene_data: 0
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.rolluiken_kamer_rens
- alias: Button 4 hold
  initial_state: true
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad_3
      scene_id: 4
      scene_data: 2
  action:
  - service: light.toggle
    data:
      entity_id: light.hue_lightstrip_plus_1
