##### Alarm DISARM automations #########################
- alias: Alarm disarmed
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
    - service: notify.mobile_app_iphone_x_alexander
      data:
        title: 'Alarm!'
        message: 'The alarm is Disarmed at {{now().strftime("%H:%M %d-%m-%Y")}}'
        data:
          subtitle: 'DISARMED'
    - service: light.turn_off
      entity_id: light.spot_kek_amsterdam
    - service: switch.turn_off
      entity_id: switch.aeon_labs_zw080_siren_gen5_switch_3

##### TRIGGER Alarm automations ########################
- alias: Trigger while armed for night
  trigger:
    - platform: state
      entity_id: sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control
      to: '22'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: 'armed_night'
    - condition: state
      entity_id: device_tracker.iphone_x_alexander_2
      state: 'home'
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.mobile_app_iphone_x_alexander
      data:
        title: 'ALARM!'
        message: 'The alarm is triggerd at {{now().strftime("%H:%M %d-%m-%Y")}}'
        data:
          subtitle: 'The alarm is triggerd'
    - service: script.sonos_say
      data:
        sonos_entity: media_player.speakers
        volume: 0.4
        message: 'ATTENTIE!! Inbraak gedetecteerd, de politie is ingeschakeld.'
        delay: '00:00:05'
    - service: switch.turn_on
      data:
        entity_id: switch.aeon_labs_zw080_siren_gen5_switch_3
    - service: light.turn_on
      data:
        entity_id: light.kek_amsterdam,light.hue_lightstrip_plus_1
        rgb_color: [255,0,0]
        brightness: 255
        flash: long
