- alias: Stairway evening
  trigger:
    platform: sun
    event: sunset
    offset: "+00:45:00"
  condition:
    condition: state
    entity_id: device_tracker.iphone_x_alexander_2
    state: home
  action:
    service: light.turn_on
    entity_id: light.hue_lightstrip_plus_1
    data:
      brightness: 33
- alias: Stairway morning
  trigger:
    platform: sun
    event: sunrise
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: device_tracker.iphone_x_alexander_2
    state: home
  action:
    service: light.turn_on
    entity_id: light.hue_lightstrip_plus_1
    data:
      brightness: 33
